language: erlang
install: "sudo pip install codecov"
script:
  - make
  - make dialyze
  - make tests COVER=1
otp_release:
  - 21.0

after_success: "escript ./deps/covertool/ebin/covertool.beam -cover ./eunit.coverdata -output cobertura.xml -appname erlpusher -src ./src && codecov"
